export interface GolfCourse {
  site_name: string;
  town: string;
  easting: number;
  northing: number;
  facility_sub_type: string;
}

export const golfCourses: GolfCourse[] = [
{ site_name:	"Aberdeen Ladies' Golf Club"	,	town:	"Aberdeen"	,	easting:	394939	,	northing:	809924	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aberdeen Ladies' Golf Club"	,	town:	"Aberdeen"	,	easting:	394939	,	northing:	809924	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Auchmill Golf Course"	,	town:	"ABERDEEN"	,	easting:	389600	,	northing:	808900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Balnagask Golf Course"	,	town:	"Aberdeen"	,	easting:	395925	,	northing:	805162	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craibstone Golf Centre"	,	town:	"Aberdeen"	,	easting:	386445	,	northing:	810328	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Deeside Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	388400	,	northing:	802200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Deeside Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	388400	,	northing:	802200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hazelhead Golf Course"	,	town:	"NR ABERDEEN"	,	easting:	389200	,	northing:	805500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hazelhead Golf Course"	,	town:	"NR ABERDEEN"	,	easting:	389200	,	northing:	805500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hazelhead Golf Course"	,	town:	"NR ABERDEEN"	,	easting:	389200	,	northing:	805500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kings Links Golf Course"	,	town:	"ABERDEEN"	,	easting:	394900	,	northing:	807500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kippie Lodge Sports & Country Club"	,	town:	"NR ABERDEEN"	,	easting:	384781	,	northing:	801439	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Murcar Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	395700	,	northing:	812200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Murcar Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	395700	,	northing:	812200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Nigg Bay Golf Course"	,	town:	"ABERDEEN"	,	easting:	396000	,	northing:	805400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Peterculter Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	383700	,	northing:	799500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Aberdeen Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	395000	,	northing:	809800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Aberdeen Golf Club"	,	town:	"NR ABERDEEN"	,	easting:	395000	,	northing:	809800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aboyne Golf Club"	,	town:	"ABOYNE"	,	easting:	353400	,	northing:	799400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Alford Golf Club"	,	town:	"ALFORD"	,	easting:	357800	,	northing:	816300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aspire Golf Centre"	,	town:	"NR ABERDEEN"	,	easting:	389816	,	northing:	802276	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Auchenblae Golf Club"	,	town:	"LAURENCEKIRK"	,	easting:	373100	,	northing:	779100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ballater Golf Club"	,	town:	"BALLATER"	,	easting:	336700	,	northing:	795400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ballindalloch Castle Golf Course"	,	town:	"NR ABERLOUR"	,	easting:	317898	,	northing:	835789	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Balmoral Golf Course"	,	town:	"NR BALLATER"	,	easting:	326300	,	northing:	794500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Banchory Golf Club"	,	town:	"Banchory"	,	easting:	369188	,	northing:	795563	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Braemar Golf Club"	,	town:	"BRAEMAR"	,	easting:	314900	,	northing:	790300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cheyne Hill Golf Club"	,	town:	"STONEHAVEN"	,	easting:	383500	,	northing:	787400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cruden Bay Golf Club"	,	town:	"CRUDEN BAY"	,	easting:	408200	,	northing:	835900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cruden Bay Golf Club"	,	town:	"CRUDEN BAY"	,	easting:	408200	,	northing:	835900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Duff House Royal Golf Club"	,	town:	"BANFF"	,	easting:	369000	,	northing:	863600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunecht House Golf Club"	,	town:	"ECHT"	,	easting:	375400	,	northing:	807700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fraserburgh Golf Club"	,	town:	"FRASERBURGH"	,	easting:	400561	,	northing:	865307	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fraserburgh Golf Club"	,	town:	"FRASERBURGH"	,	easting:	400561	,	northing:	865307	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fyvie Golf Club"	,	town:	"Turriff"	,	easting:	376644	,	northing:	837760	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Huntly Golf Club"	,	town:	"Huntly"	,	easting:	353096	,	northing:	840417	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Inchmarlo Golf Centre"	,	town:	"BANCHORY"	,	easting:	368054	,	northing:	796614	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Inchmarlo Golf Centre"	,	town:	"BANCHORY"	,	easting:	368054	,	northing:	796614	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Insch Golf Club"	,	town:	"INSCH"	,	easting:	362500	,	northing:	828500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Inverallochy Golf Club & Invercairn Bowling Club"	,	town:	"FRASERBURGH"	,	easting:	404600	,	northing:	864700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kemnay Golf Club"	,	town:	"KEMNAY"	,	easting:	372900	,	northing:	815600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kintore Golf Club"	,	town:	"KINTORE"	,	easting:	380000	,	northing:	816700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Longside Golf Club"	,	town:	"LONGSIDE"	,	easting:	403300	,	northing:	847700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lumphanan Golf Club"	,	town:	"NR TORPHINS"	,	easting:	358800	,	northing:	804300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Mcdonald Golf Club"	,	town:	"ELLON"	,	easting:	395100	,	northing:	831200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Meldrum House Hotel and Golf Club"	,	town:	"OLDMELDRUM"	,	easting:	381199	,	northing:	829064	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newburgh-on-Ythan Golf Club"	,	town:	"NR ELLON"	,	easting:	400200	,	northing:	825200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newburgh-on-Ythan Golf Club"	,	town:	"NR ELLON"	,	easting:	400200	,	northing:	825200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newmachar Golf Club"	,	town:	"Aberdeen"	,	easting:	388151	,	northing:	817022	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newmachar Golf Club"	,	town:	"Aberdeen"	,	easting:	388151	,	northing:	817022	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newmacher Golf Club"	,	town:	"NEWMACHER"	,	easting:	388200	,	northing:	817000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Oldmeldrum Golf Club"	,	town:	"OLDMELDRUM"	,	easting:	381400	,	northing:	827300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Peterhead Golf Club"	,	town:	"PETERHEAD"	,	easting:	411900	,	northing:	847500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Peterhead Golf Club"	,	town:	"PETERHEAD"	,	easting:	411900	,	northing:	847500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Portlethen Golf Club"	,	town:	"PORTLETHEN"	,	easting:	392500	,	northing:	798300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Tarlair Golf Club"	,	town:	"MACDUFF"	,	easting:	371400	,	northing:	864600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Stonehaven Golf Club"	,	town:	"STONEHAVEN"	,	easting:	388495	,	northing:	788670	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tarland Golf Club"	,	town:	"NR ABOYNE"	,	easting:	348300	,	northing:	804600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Torphins Golf Club"	,	town:	"Banchory"	,	easting:	361557	,	northing:	802701	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Trump International Golf Links"	,	town:	"Aberdeen"	,	easting:	398011	,	northing:	820343	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Turriff Golf Club"	,	town:	"TURRIFF"	,	easting:	371200	,	northing:	849800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Westhill Golf Club"	,	town:	"WESTHILL"	,	easting:	382400	,	northing:	807800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Arbroath Artisan Golf Club"	,	town:	"NR ARBROATH"	,	easting:	361600	,	northing:	739200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Arbroath Pitch and Putt Golf Course"	,	town:	"Arbroath"	,	easting:	364368	,	northing:	742082	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Brechin Golf and Squash Club"	,	town:	"BRECHIN"	,	easting:	360300	,	northing:	762000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carnoustie Golf Links"	,	town:	"CARNOUSTIE"	,	easting:	355500	,	northing:	734100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carnoustie Golf Links"	,	town:	"CARNOUSTIE"	,	easting:	355500	,	northing:	734100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carnoustie Golf Links"	,	town:	"CARNOUSTIE"	,	easting:	355500	,	northing:	734100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Edzell Golf Club"	,	town:	"EDZELL"	,	easting:	359900	,	northing:	768400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Edzell Golf Club"	,	town:	"EDZELL"	,	easting:	359900	,	northing:	768400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Forfar Golf Club"	,	town:	"FORFAR"	,	easting:	347900	,	northing:	750600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kingennie Golf Club"	,	town:	"Dundee"	,	easting:	347895	,	northing:	736147	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kirriemuir Golf Club"	,	town:	"KIRRIEMUIR"	,	easting:	338800	,	northing:	755400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Letham Grange Hotel and Golf Courses"	,	town:	"NR ARBROATH"	,	easting:	353000	,	northing:	748500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Letham Grange Hotel and Golf Courses"	,	town:	"NR ARBROATH"	,	easting:	353000	,	northing:	748500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Monifieth Golf Courses"	,	town:	"MONIFIETH"	,	easting:	350300	,	northing:	732600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Monifieth Golf Courses"	,	town:	"MONIFIETH"	,	easting:	350300	,	northing:	732600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Montrose Links Trust"	,	town:	"MONTROSE"	,	easting:	372300	,	northing:	758200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Montrose Links Trust"	,	town:	"MONTROSE"	,	easting:	372300	,	northing:	758200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Panmure Golf Club"	,	town:	"NR CARNOUSTIE"	,	easting:	353700	,	northing:	733900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Piperdam Golf & Leisure Resort"	,	town:	"Dundee"	,	easting:	330349	,	northing:	734702	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Blairmore & Strone Golf Club"	,	town:	"DUNOON"	,	easting:	219100	,	northing:	681200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bute Golf Club"	,	town:	"ROTHESAY"	,	easting:	208196	,	northing:	656215	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cardross Golf Club"	,	town:	"CARDROSS"	,	easting:	234700	,	northing:	677400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carradale Golf Club"	,	town:	"NR CAMBELTOWN"	,	easting:	181500	,	northing:	638400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Colonsay Golf Club"	,	town:	"COLONSAY"	,	easting:	135700	,	northing:	693600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cowal Golf Club"	,	town:	"DUNOON"	,	easting:	217900	,	northing:	678300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craignure Golf Club"	,	town:	"CRAIGNURE"	,	easting:	150000	,	northing:	755000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dalmally Golf Club"	,	town:	"DALMALLY"	,	easting:	215200	,	northing:	727600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Drimsynie House Hotel"	,	town:	"Lochgoilhead"	,	easting:	219220	,	northing:	701563	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunaverty Golf Club"	,	town:	"NR CAMBELTOWN"	,	easting:	168900	,	northing:	607600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gigha Golf Club"	,	town:	"GIGHA"	,	easting:	164000	,	northing:	647000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glencruitten Golf Club"	,	town:	"OBAN"	,	easting:	186800	,	northing:	729700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Helensburgh Golf Club"	,	town:	"Helensburgh"	,	easting:	230700	,	northing:	683100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Innellan Golf Club"	,	town:	"INNELLAN"	,	easting:	215200	,	northing:	671100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Inveraray Golf Club"	,	town:	"INVERARAY"	,	easting:	209500	,	northing:	708500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Isle of Eriska Hotel Spa and Golf"	,	town:	"NR OBAN"	,	easting:	190284	,	northing:	743175	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Isle of Seil Golf Club"	,	town:	"NR OBAN"	,	easting:	176931	,	northing:	716671	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kyles of Bute Golf Club"	,	town:	"TIGHNABRUAICH"	,	easting:	197300	,	northing:	672600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Loch Lomond Golf Club"	,	town:	"Alexandria"	,	easting:	235165	,	northing:	689985	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochgilphead Golf Club"	,	town:	"LOCHGILPHEAD"	,	easting:	187300	,	northing:	688700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochgoilhead Golf Course"	,	town:	"Cairndow"	,	easting:	217635	,	northing:	701907	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Machrie Hotel and Golf Links"	,	town:	"PORT ELLEN"	,	easting:	120800	,	northing:	663900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Machrihanish Dunes Golf Club"	,	town:	"Campbeltown"	,	easting:	165861	,	northing:	624300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Machrihanish Golf Club"	,	town:	"Machrihanish"	,	easting:	163920	,	northing:	620792	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Machrihanish Golf Club"	,	town:	"Machrihanish"	,	easting:	163920	,	northing:	620792	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Port Bannatyne Golf Club"	,	town:	"PORT BANNATYNE"	,	easting:	206900	,	northing:	667000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tarbert Golf Club"	,	town:	"TARBERT"	,	easting:	184600	,	northing:	668400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Taynuilt Golf Club"	,	town:	"NR OBAN"	,	easting:	200500	,	northing:	731800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tobermory Golf Club"	,	town:	"TOBERMORY"	,	easting:	150800	,	northing:	755700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Vaul Golf Club"	,	town:	"TIREE"	,	easting:	108500	,	northing:	748300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Baberton Golf Club"	,	town:	"NR EDINBURGH"	,	easting:	319700	,	northing:	668900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bruntsfield Links Golfing Society"	,	town:	"EDINBURGH"	,	easting:	319900	,	northing:	675700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carricknowe Golf Club"	,	town:	"EDINBURGH"	,	easting:	321600	,	northing:	672300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craigentinny Golf Course"	,	town:	"EDINBURGH"	,	easting:	329000	,	northing:	675200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craigmillar Park Golf Club"	,	town:	"EDINBURGH"	,	easting:	326400	,	northing:	670700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Duddingston Golf Club"	,	town:	"EDINBURGH"	,	easting:	329100	,	northing:	672100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dundas Parks Golf Club"	,	town:	"EDINBURGH"	,	easting:	312500	,	northing:	676700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gogarburn Golf Club"	,	town:	"Newbridge"	,	easting:	315861	,	northing:	671725	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hermitage Family Golf Course"	,	town:	"Edinburgh"	,	easting:	325432	,	northing:	669787	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kingsknowe Golf Club"	,	town:	"Edinburgh"	,	easting:	321100	,	northing:	669700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Liberton Golf Club"	,	town:	"EDINBURGH"	,	easting:	328300	,	northing:	670100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lothianburn Golf Club"	,	town:	"EDINBURGH"	,	easting:	324900	,	northing:	667200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Marriott Dalmahoy Hotel And Country Club"	,	town:	"Nr Edinburgh"	,	easting:	314400	,	northing:	668700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Marriott Dalmahoy Hotel And Country Club"	,	town:	"Nr Edinburgh"	,	easting:	314400	,	northing:	668700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Merchants of Edinburgh Golf Club"	,	town:	"EDINBURGH"	,	easting:	323600	,	northing:	670300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Mortonhall Golf Club"	,	town:	"EDINBURGH"	,	easting:	324400	,	northing:	669300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Murrayfield Golf Club"	,	town:	"EDINBURGH"	,	easting:	321900	,	northing:	673700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Portobello Golf Course"	,	town:	"EDINBURGH"	,	easting:	330500	,	northing:	673000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Prestonfield Golf Club"	,	town:	"EDINBURGH"	,	easting:	327200	,	northing:	672100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ratho Park Golf Club"	,	town:	"RATHO"	,	easting:	315000	,	northing:	670800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ravelston Golf Club"	,	town:	"EDINBURGH"	,	easting:	321500	,	northing:	674000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Burgess Golfing Society of Edinburgh"	,	town:	"EDINBURGH"	,	easting:	318500	,	northing:	675100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Silverknowes Golf Club"	,	town:	"EDINBURGH"	,	easting:	320700	,	northing:	676300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Swanston Golf Club"	,	town:	"EDINBURGH"	,	easting:	323900	,	northing:	667400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Swanston Golf Club"	,	town:	"EDINBURGH"	,	easting:	323900	,	northing:	667400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Turnhouse Golf Club"	,	town:	"EDINBURGH"	,	easting:	316700	,	northing:	673800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Alloa Golf Club"	,	town:	"ALLOA"	,	easting:	289900	,	northing:	694500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Alva Golf Club"	,	town:	"ALVA"	,	easting:	288300	,	northing:	697400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Braehead Golf Club"	,	town:	"ALLOA"	,	easting:	286300	,	northing:	694000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dollar Golf Club"	,	town:	"DOLLAR"	,	easting:	296300	,	northing:	698300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muckhart Golf Club"	,	town:	"NR DOLLAR"	,	easting:	300300	,	northing:	700100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muckhart Golf Club"	,	town:	"NR DOLLAR"	,	easting:	300300	,	northing:	700100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muckhart Golf Club"	,	town:	"NR DOLLAR"	,	easting:	300300	,	northing:	700100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tillicoultry Golf Club"	,	town:	"TILLICOULTRY"	,	easting:	291300	,	northing:	697100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Askernish Golf Club"	,	town:	"Isle of South Uist"	,	easting:	73270	,	northing:	823098	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Benbecula Golf Club"	,	town:	"Isle of Benbecula"	,	easting:	76450	,	northing:	853666	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Harris Golf Club"	,	town:	"TARBERT"	,	easting:	101146	,	northing:	893610	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Isle of Barra Golf Club"	,	town:	"Isle of Barra"	,	easting:	66995	,	northing:	804423	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Stornoway Golf Club"	,	town:	"STORNOWAY"	,	easting:	142300	,	northing:	935500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Brighouse Bay Golf Club/Holiday Park"	,	town:	"KIRKCUDBRIGHT"	,	easting:	263200	,	northing:	545600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cally Palace Hotel"	,	town:	"Castle Douglas"	,	easting:	259898	,	northing:	555063	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Castle Douglas Golf Club"	,	town:	"Castle Douglas"	,	easting:	275656	,	northing:	562874	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Colvend Golf Club"	,	town:	"DALBEATTIE"	,	easting:	288500	,	northing:	554900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crichton Golf Club"	,	town:	"DUMFRIES"	,	easting:	298400	,	northing:	574100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dalbeattie Golf Club"	,	town:	"Dalbeattie"	,	easting:	282632	,	northing:	561988	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dumfries & County Golf Club"	,	town:	"DUMFRIES"	,	easting:	297700	,	northing:	577400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dumfries & Galloway Golf Club"	,	town:	"DUMFRIES"	,	easting:	296200	,	northing:	575700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gatehouse of Fleet Golf Club"	,	town:	"GATEHOUSE OF FLEET"	,	easting:	260100	,	northing:	557200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hoddom Castle Golf Club"	,	town:	"LOCKERBIE"	,	easting:	315500	,	northing:	573000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kirkcudbright Golf Club"	,	town:	"KIRKCUDBRIGHT"	,	easting:	268900	,	northing:	551400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lagganmore Golf Club"	,	town:	"PORTPATRICK"	,	easting:	201700	,	northing:	554000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Langholm Golf Club"	,	town:	"LANGHOLM"	,	easting:	336600	,	northing:	584600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Moffat Golf Club"	,	town:	"MOFFAT"	,	easting:	307600	,	northing:	604700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"New Galloway Golf Club"	,	town:	"NR CASTLE DOUGLAS"	,	easting:	263300	,	northing:	577100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newton Stewart Golf Club"	,	town:	"NEWTON STEWART"	,	easting:	241000	,	northing:	566000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Portpatrick (Dunskey) Golf Club"	,	town:	"PORTPATRICK"	,	easting:	199700	,	northing:	554500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Portpatrick (Dunskey) Golf Club"	,	town:	"PORTPATRICK"	,	easting:	199700	,	northing:	554500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Powfoot Golf Club"	,	town:	"ANNAN"	,	easting:	314000	,	northing:	565600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Sanquhar Golf Club"	,	town:	"SANQUHAR"	,	easting:	277300	,	northing:	609400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Southerness Golf Club"	,	town:	"DUMFRIES"	,	easting:	296900	,	northing:	554900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Medan Golf Club"	,	town:	"NEWTON STEWART"	,	easting:	236600	,	northing:	539800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Stranraer Golf Club"	,	town:	"STRANRAER"	,	easting:	203400	,	northing:	563200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Thornhill Golf Club"	,	town:	"Thornhill"	,	easting:	287605	,	northing:	598188	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Wigtown & Bladnoch Golf Club"	,	town:	"WIGTOWN"	,	easting:	243000	,	northing:	554900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Wigtownshire County Golf Club"	,	town:	"GLENLUCE"	,	easting:	218200	,	northing:	556000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ballumbie Castle Golf Course"	,	town:	"Dundee"	,	easting:	344071	,	northing:	733956	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Camperdown Country Park"	,	town:	"Dundee"	,	easting:	336136	,	northing:	732980	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Downfield Golf Club"	,	town:	"DUNDEE"	,	easting:	336800	,	northing:	733400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Regional Performance Centre - Caird Park"	,	town:	"DUNDEE"	,	easting:	341200	,	northing:	732800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Annanhill Golf Course"	,	town:	"KILMARNOCK"	,	easting:	241300	,	northing:	637900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ballochmyle Golf Club"	,	town:	"MAUCHLINE"	,	easting:	251300	,	northing:	626400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Caprington Golf Course"	,	town:	"KILMARNOCK"	,	easting:	242300	,	northing:	635800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Caprington Golf Course"	,	town:	"KILMARNOCK"	,	easting:	242300	,	northing:	635800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Doon Valley, Patna Golf Club"	,	town:	"PATNA"	,	easting:	241819	,	northing:	610284	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Loudoun Golf Club"	,	town:	"GALSTON"	,	easting:	250900	,	northing:	637200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muirkirk Golf Club"	,	town:	"MUIRKIRK"	,	easting:	269600	,	northing:	627000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"New Cumnock Golf Club"	,	town:	"NEW CUMNOCK"	,	easting:	260700	,	northing:	614600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Rowallan Castle Golf Club"	,	town:	"Kilmarnock"	,	easting:	242950	,	northing:	642963	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Balmore Golf Club"	,	town:	"NR TORRANCE"	,	easting:	259500	,	northing:	673900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bearsden Golf Club"	,	town:	"BEARSDEN"	,	easting:	253200	,	northing:	672200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bishopbriggs Golf Club"	,	town:	"BISHOPBRIGGS"	,	easting:	260600	,	northing:	670600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Campsie Golf Club"	,	town:	"LENNOXTOWN"	,	easting:	262900	,	northing:	678500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cawder Golf Club"	,	town:	"BISHOPBRIGGS"	,	easting:	260500	,	northing:	672700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cawder Golf Club"	,	town:	"BISHOPBRIGGS"	,	easting:	260500	,	northing:	672700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Clober Golf Club"	,	town:	"MILNGAVIE"	,	easting:	254700	,	northing:	675000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Douglas Park Golf Club"	,	town:	"BEARSDEN"	,	easting:	255300	,	northing:	672200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Esporta Dougalston Golf Club"	,	town:	"Glasgow"	,	easting:	256538	,	northing:	675277	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glasgow Golf Club"	,	town:	"BEARSDEN"	,	easting:	256200	,	northing:	670700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hayston Golf Club"	,	town:	"KIRKINTILLOCH"	,	easting:	264300	,	northing:	674300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hilton Park Golf Club"	,	town:	"MILNGAVIE"	,	easting:	252600	,	northing:	677600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hilton Park Golf Club"	,	town:	"MILNGAVIE"	,	easting:	252600	,	northing:	677600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kirkintilloch Golf Club"	,	town:	"KIRKINTILLOCH"	,	easting:	264600	,	northing:	674500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lenzie Golf Club"	,	town:	"KIRKINTILLOCH"	,	easting:	265700	,	northing:	671100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Milngavie Golf Club"	,	town:	"MILNGAVIE"	,	easting:	253800	,	northing:	676600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Windyhill Golf Club"	,	town:	"BEARSDEN"	,	easting:	252200	,	northing:	673600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Archerfield Links"	,	town:	", "	,	easting:	350143	,	northing:	683837	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Archerfield Links"	,	town:	", "	,	easting:	350143	,	northing:	683837	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Castle Park Golf Course"	,	town:	"GIFFORD"	,	easting:	355078	,	northing:	666191	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craigielaw Golf Club"	,	town:	"Longniddry"	,	easting:	345416	,	northing:	679744	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunbar Golf Club"	,	town:	"DUNBAR"	,	easting:	368900	,	northing:	678400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gifford Golf Club"	,	town:	"GIFFORD"	,	easting:	352700	,	northing:	667400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glen Golf Club"	,	town:	"NORTH BERWICK"	,	easting:	356068	,	northing:	685180	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gullane Golf Club"	,	town:	"GULLANE"	,	easting:	348000	,	northing:	682600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gullane Golf Club"	,	town:	"GULLANE"	,	easting:	348000	,	northing:	682600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gullane Golf Club"	,	town:	"GULLANE"	,	easting:	348000	,	northing:	682600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Haddington Golf Club"	,	town:	"HADDINGTON"	,	easting:	352800	,	northing:	674200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kilspindie Golf Club"	,	town:	"ABERLADY"	,	easting:	345600	,	northing:	680200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Longniddry Golf Club"	,	town:	"LONGNIDDRY"	,	easting:	343700	,	northing:	676400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Luffness New Golf Club"	,	town:	"ABERLADY"	,	easting:	347800	,	northing:	681200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muirfield Golf Club"	,	town:	"Gullane"	,	easting:	349081	,	northing:	683573	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muirfield Golf Course"	,	town:	"Gullane"	,	easting:	348875	,	northing:	683453	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Musselburgh Old Course"	,	town:	"MUSSELBURGH"	,	easting:	335200	,	northing:	673100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"North Berwick Golf Club"	,	town:	"North Berwick"	,	easting:	354866	,	northing:	685317	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"North Berwick Golf Club"	,	town:	"North Berwick"	,	easting:	354866	,	northing:	685317	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Renaissance Golf Club"	,	town:	"North Berwick"	,	easting:	349625	,	northing:	684365	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Musselburgh Golf Club"	,	town:	"PRESTONPANS"	,	easting:	337800	,	northing:	673600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tantallon Golf Club"	,	town:	"North Berwick"	,	easting:	354758	,	northing:	685279	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Winterfield Golf Club"	,	town:	"DUNBAR"	,	easting:	367100	,	northing:	679000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bonnyton Golf Club"	,	town:	"EAGLESHAM"	,	easting:	255100	,	northing:	652100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Caldwell Golf Club"	,	town:	"Glasgow"	,	easting:	242680	,	northing:	654950	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cathcart Castle Golf Club"	,	town:	"CLARKSTON"	,	easting:	256300	,	northing:	657300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Deaconsbank Golf Course"	,	town:	"THORNLIEBANK"	,	easting:	254400	,	northing:	658500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"East Renfrewshire Golf Club"	,	town:	"NEWTON MEARNS"	,	easting:	251800	,	northing:	652600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fereneze Golf Club"	,	town:	"BARRHEAD"	,	easting:	249200	,	northing:	659300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Mearns Castle Golf Academy"	,	town:	"Glasgow"	,	easting:	256331	,	northing:	655303	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Rouken Glen Golf Centre"	,	town:	"Glasgow"	,	easting:	254116	,	northing:	658431	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Whitecraigs Golf Club"	,	town:	"GIFFNOCK"	,	easting:	256200	,	northing:	657200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Whitecraigs Golf Club"	,	town:	"GIFFNOCK"	,	easting:	256200	,	northing:	657200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Williamwood Golf Club"	,	town:	"CLARKSTON"	,	easting:	257500	,	northing:	658500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bonnybridge Golf Club"	,	town:	"BONNYBRIDGE"	,	easting:	282900	,	northing:	681200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Falkirk Golf Club"	,	town:	"FALKIRK"	,	easting:	286700	,	northing:	680900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Falkirk Tryst Golf Club"	,	town:	"LARBERT"	,	easting:	286300	,	northing:	683100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glenbervie Golf Club"	,	town:	"LARBERT"	,	easting:	284600	,	northing:	683900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Grangemouth Golf Club"	,	town:	"NR FALKIRK"	,	easting:	294700	,	northing:	679200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Polmont Golf Club"	,	town:	"FALKIRK"	,	easting:	293900	,	northing:	676400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aberdour Golf Club"	,	town:	"ABERDOUR"	,	easting:	319100	,	northing:	684700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Anstruther Golf Club"	,	town:	"ANSTRUTHER"	,	easting:	356200	,	northing:	703200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Auchterderran Golf Course"	,	town:	"CARDENDEN"	,	easting:	321000	,	northing:	696200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Balbirnie Park Golf Club"	,	town:	"GLENROTHES"	,	easting:	329000	,	northing:	702700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Burntisland Golf Club"	,	town:	"BURNTISLAND"	,	easting:	323900	,	northing:	686800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Canmore Golf Club"	,	town:	"DUNFERMLINE"	,	easting:	309400	,	northing:	688800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Charleton Golf Course"	,	town:	"LEVEN"	,	easting:	346300	,	northing:	703600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cluny Clays Activity Centre"	,	town:	"NR KIRKCALDY"	,	easting:	324658	,	northing:	696566	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cowdenbeath Golf Club"	,	town:	"Cowdenbeath"	,	easting:	316902	,	northing:	692028	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crail Golfing Society"	,	town:	"CRAIL"	,	easting:	363400	,	northing:	709800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crail Golfing Society"	,	town:	"CRAIL"	,	easting:	363400	,	northing:	709800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cupar Golf Club"	,	town:	"CUPAR"	,	easting:	337700	,	northing:	713500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Drumoig Golf Course"	,	town:	"ST ANDREWS"	,	easting:	343992	,	northing:	725167	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Duke's Golf Course"	,	town:	"St Andrews"	,	easting:	347825	,	northing:	714479	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunfermline Golf Club"	,	town:	"DUNFERMLINE"	,	easting:	306300	,	northing:	686300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunfermline Golf Club"	,	town:	"DUNFERMLINE"	,	easting:	306300	,	northing:	686300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunnikier Park Golf Course"	,	town:	"KIRKCALDY"	,	easting:	327900	,	northing:	694300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Elie Golf House Club"	,	town:	"Leven"	,	easting:	348590	,	northing:	700122	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Elie Golf House Club"	,	town:	"Leven"	,	easting:	348590	,	northing:	700122	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Elmwood College Golf Course"	,	town:	"CUPAR"	,	easting:	335142	,	northing:	712250	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Falkland Golf Club"	,	town:	"FALKLAND"	,	easting:	325600	,	northing:	707500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Forrester Park Resort"	,	town:	"CAIRNEYHILL"	,	easting:	304597	,	northing:	686973	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glenrothes Golf Course"	,	town:	"GLENROTHES"	,	easting:	325100	,	northing:	700100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kingarrock Hickory Golf Course"	,	town:	"Cupar"	,	easting:	337686	,	northing:	711758	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kinghorn Golf Course"	,	town:	"KINGHORN"	,	easting:	326600	,	northing:	686500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kingsbarns Golf Links"	,	town:	"ST ANDREWS"	,	easting:	360107	,	northing:	711989	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ladybank Golf Club"	,	town:	"LADYBANK"	,	easting:	330400	,	northing:	710500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Leslie Golf Club"	,	town:	"GLENROTHES"	,	easting:	324800	,	northing:	702100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Leven Links"	,	town:	"LEVEN"	,	easting:	338600	,	northing:	701300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochgelly Golf Club"	,	town:	"LOCHGELLY"	,	easting:	318100	,	northing:	693500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochore Meadows Golf Course"	,	town:	"LOCHGELLY"	,	easting:	317100	,	northing:	696200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lundin Golf Club"	,	town:	"LUNDIN LINKS"	,	easting:	340900	,	northing:	702500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lundin Ladies Golf Club"	,	town:	"LUNDIN LINKS"	,	easting:	341000	,	northing:	702800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Pitreavie (Dunfermline) Golf Club"	,	town:	"DUNFERMLINE"	,	easting:	310500	,	northing:	685600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Saline Golf Club"	,	town:	"SALINE"	,	easting:	302800	,	northing:	692200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Scoonie Golf Course"	,	town:	"LEVEN"	,	easting:	338700	,	northing:	701500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Scotscraig Golf Club"	,	town:	"TAYPORT"	,	easting:	346100	,	northing:	728000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Bay (Fairmont) "	,	town:	"St Andrews"	,	easting:	354692	,	northing:	714585	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Bay (Fairmont) "	,	town:	"St Andrews"	,	easting:	354692	,	northing:	714585	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Links Trust"	,	town:	"ST ANDREWS"	,	easting:	350400	,	northing:	717100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Links Trust"	,	town:	"ST ANDREWS"	,	easting:	350400	,	northing:	717100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Links Trust"	,	town:	"ST ANDREWS"	,	easting:	350400	,	northing:	717100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Links Trust"	,	town:	"ST ANDREWS"	,	easting:	350400	,	northing:	717100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Andrews Links Trust"	,	town:	"ST ANDREWS"	,	easting:	350400	,	northing:	717100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Michaels Golf Club"	,	town:	"LEUCHARS"	,	easting:	344600	,	northing:	722000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Thornton Golf Club"	,	town:	"THORNTON"	,	easting:	330000	,	northing:	697600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tulliallan Golf Club"	,	town:	"KINCARDINE"	,	easting:	293000	,	northing:	688400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Alexandra Park Golf Course"	,	town:	"GLASGOW"	,	easting:	262200	,	northing:	665900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cowglen Golf Club"	,	town:	"Glasgow"	,	easting:	254701	,	northing:	661191	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Haggs Castle Golf Club"	,	town:	"GLASGOW"	,	easting:	255000	,	northing:	662800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Knightswood Golf Course"	,	town:	"GLASGOW"	,	easting:	253000	,	northing:	668900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lethamhill Golf Club"	,	town:	"GLASGOW"	,	easting:	263900	,	northing:	666600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Linn Park Golf Club"	,	town:	"GLASGOW"	,	easting:	258800	,	northing:	659200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Littlehill Golf Club"	,	town:	"BISHOPBRIGGS"	,	easting:	261400	,	northing:	669300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Pollok Golf Club"	,	town:	"GLASGOW"	,	easting:	255500	,	northing:	661100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Sandyhills Golf Club"	,	town:	"GLASGOW"	,	easting:	265400	,	northing:	663400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Abernethy Golf Club"	,	town:	"NETHY BRIDGE"	,	easting:	300371	,	northing:	821108	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aigas Golf Course"	,	town:	"NR BEAULY"	,	easting:	246400	,	northing:	842600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Alness Golf Club"	,	town:	"ALNESS"	,	easting:	265300	,	northing:	870300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Boat of Garten Golf & Tennis Club"	,	town:	"BOAT OF GARTEN"	,	easting:	294397	,	northing:	819048	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bonar Bridge/Ardgay Golf Club"	,	town:	"BONAR BRIDGE"	,	easting:	261700	,	northing:	891600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Brahan Golf Club"	,	town:	"Dingwall"	,	easting:	251755	,	northing:	856355	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Brora Golf Club"	,	town:	"BRORA"	,	easting:	291000	,	northing:	904000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carnegie Club"	,	town:	"DORNOCH"	,	easting:	273086	,	northing:	887412	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carrbridge Golf Club"	,	town:	"CARRBRIDGE"	,	easting:	290500	,	northing:	823000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Castle Stuart Golf Links"	,	town:	"Inverness"	,	easting:	275062	,	northing:	850734	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cawdor Castle Golf Course"	,	town:	"CAWDOR"	,	easting:	284000	,	northing:	849000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craggan Golf Course"	,	town:	"GRANTOWN ON SPEY"	,	easting:	301940	,	northing:	825850	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dalfaber Golf and Country Club"	,	town:	"Aviemore"	,	easting:	290385	,	northing:	813885	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dragon's Tooth Golf Course"	,	town:	"BALLACHULISH"	,	easting:	204818	,	northing:	759405	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Durness Golf Club"	,	town:	"DURNESS"	,	easting:	239300	,	northing:	968600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fairways Leisure"	,	town:	"Inverness"	,	easting:	267193	,	northing:	842468	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fairways Leisure"	,	town:	"Inverness"	,	easting:	267193	,	northing:	842468	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fort Augustus Golf Club"	,	town:	"FORT AUGUSTUS"	,	easting:	237200	,	northing:	808300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fort William Golf Club"	,	town:	"FORT WILLIAM"	,	easting:	213600	,	northing:	776200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Fortrose and Rosemarkie Golf Club"	,	town:	"Fortrose"	,	easting:	274008	,	northing:	856664	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gairloch Golf Club"	,	town:	"GAIRLOCH"	,	easting:	180600	,	northing:	875600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Golspie Golf Club"	,	town:	"GOLSPIE"	,	easting:	282300	,	northing:	899000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Grantown on Spey Golf Club"	,	town:	"GRANTOWN ON SPEY"	,	easting:	303800	,	northing:	828000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Helmsdale Golf Club"	,	town:	"HELMSDALE"	,	easting:	302400	,	northing:	915800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Invergordon Golf Club"	,	town:	"INVERGORDON"	,	easting:	269600	,	northing:	868900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Inverness Golf Club"	,	town:	"INVERNESS"	,	easting:	268077	,	northing:	844659	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Isle of Skye Golf Club"	,	town:	"PORTREE"	,	easting:	153500	,	northing:	832000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kingussie Golf Club"	,	town:	"KINGUSSIE"	,	easting:	275500	,	northing:	801500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochcarron Golf Club"	,	town:	"LOCHCARRON"	,	easting:	191300	,	northing:	841300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lybster Golf Club"	,	town:	"Lybster"	,	easting:	324843	,	northing:	935816	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lybster Golf Club"	,	town:	"LYBSTER"	,	easting:	325000	,	northing:	935000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Macdonald Aviemore Resort"	,	town:	"Aviemore"	,	easting:	290283	,	northing:	813416	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Macdonald Aviemore Resort"	,	town:	"Aviemore"	,	easting:	290283	,	northing:	813416	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muir of Ord Golf Club"	,	town:	"MUIR OF ORD"	,	easting:	252800	,	northing:	849600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Nairn Dunbar Golf Club"	,	town:	"NAIRN"	,	easting:	288800	,	northing:	856600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Nairn Golf Club"	,	town:	"NAIRN"	,	easting:	286700	,	northing:	856800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Nairn Golf Club"	,	town:	"NAIRN"	,	easting:	286700	,	northing:	856800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newtonmore Golf Club"	,	town:	"NEWTONMORE"	,	easting:	271700	,	northing:	798900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Reay Golf Club"	,	town:	"NR THURSO"	,	easting:	296500	,	northing:	964900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Dornoch Golf Club"	,	town:	"DORNOCH"	,	easting:	280100	,	northing:	889500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Dornoch Golf Club"	,	town:	"DORNOCH"	,	easting:	280100	,	northing:	889500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Skeabost Golf Club"	,	town:	"NR PORTREE"	,	easting:	141208	,	northing:	848717	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Spean Bridge Golf Club"	,	town:	"SPEAN BRIDGE"	,	easting:	222000	,	northing:	781300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathpeffer Spa Golf Club"	,	town:	"STRATHPEFFER"	,	easting:	248000	,	northing:	858500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tain Golf Club"	,	town:	"TAIN"	,	easting:	278600	,	northing:	882100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Tarbat Golf Course"	,	town:	"NR TAIN"	,	easting:	291800	,	northing:	884300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Thurso Golf Club"	,	town:	"THURSO"	,	easting:	309900	,	northing:	967100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Torvean Golf Club"	,	town:	"INVERNESS"	,	easting:	265200	,	northing:	843700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Traigh Golf Club"	,	town:	"ARISAIG"	,	easting:	165800	,	northing:	790100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ullapool Golf Club"	,	town:	"Ullapool"	,	easting:	212917	,	northing:	894540	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Wick Golf Club"	,	town:	"Wick"	,	easting:	334207	,	northing:	954428	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Greenock Golf Club"	,	town:	"GREENOCK"	,	easting:	226400	,	northing:	676500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Greenock Golf Club"	,	town:	"GREENOCK"	,	easting:	226400	,	northing:	676500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kilmacolm Golf Club"	,	town:	"KILMACOLM"	,	easting:	236500	,	northing:	669400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Port Glasgow Golf Club"	,	town:	"PORT GLASGOW"	,	easting:	232500	,	northing:	673300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Whinhill Golf Club"	,	town:	"GREENOCK"	,	easting:	227400	,	northing:	674600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Broomieknowe Golf Club"	,	town:	"BONNYRIGG"	,	easting:	330900	,	northing:	665800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glencorse Golf Club"	,	town:	"PENICUIK"	,	easting:	324900	,	northing:	662400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kings Acre Golf Course"	,	town:	"LASSWADE"	,	easting:	330470	,	northing:	667087	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Melville Golf Range and Golf Course"	,	town:	"Lasswade"	,	easting:	331211	,	northing:	666623	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newbattle Golf Club"	,	town:	"DALKEITH"	,	easting:	333100	,	northing:	666600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Vogrie Country Park Golf Course"	,	town:	"GOREBRIDGE"	,	easting:	337700	,	northing:	663100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Whitehill House Golf Course"	,	town:	"Rosewell"	,	easting:	329452	,	northing:	661990	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Buckpool Golf Club"	,	town:	"BUCKIE"	,	easting:	338800	,	northing:	864200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cullen Golf Club"	,	town:	"CULLEN"	,	easting:	350400	,	northing:	867300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dufftown Golf Club"	,	town:	"DUFFTOWN"	,	easting:	331000	,	northing:	839100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Elgin Golf Club"	,	town:	"Elgin"	,	easting:	321657	,	northing:	860766	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Forres Golf Club"	,	town:	"FORRES"	,	easting:	304789	,	northing:	858623	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Garmouth and Kingston Golf Club"	,	town:	"GARMOUTH"	,	easting:	334200	,	northing:	864700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Golf Dedication Centre"	,	town:	"Lossiemouth"	,	easting:	320058	,	northing:	870931	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hopeman Golf Club"	,	town:	"HOPEMAN"	,	easting:	315300	,	northing:	869500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Keith Golf Club"	,	town:	"KEITH"	,	easting:	342200	,	northing:	850600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kinloss Country Golf Club"	,	town:	"KINLOSS"	,	easting:	309666	,	northing:	863526	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Moray Golf Club"	,	town:	"LOSSIEMOUTH"	,	easting:	322900	,	northing:	870900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Moray Golf Club"	,	town:	"LOSSIEMOUTH"	,	easting:	322900	,	northing:	870900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Rothes Golf Club"	,	town:	"ROTHES"	,	easting:	327000	,	northing:	849000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Spey Bay Hotel and Golf Course"	,	town:	"FOCHABERS"	,	easting:	335500	,	northing:	865100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathlene Golf Club"	,	town:	"BUCKIE"	,	easting:	344800	,	northing:	867300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ardeer Golf Club"	,	town:	"STEVENSTON"	,	easting:	227200	,	northing:	643500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Auchenharvie Golf Course"	,	town:	"Stevenston"	,	easting:	226465	,	northing:	641470	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Beith Golf Club"	,	town:	"BEITH"	,	easting:	236800	,	northing:	655200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Corrie Golf Club"	,	town:	"NR BRODICK"	,	easting:	201500	,	northing:	645600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dundonald Links"	,	town:	"Irvine"	,	easting:	232526	,	northing:	635249	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glasgow Golf Club (Gailes)"	,	town:	"IRVINE"	,	easting:	232236	,	northing:	636166	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Irvine Golf Club"	,	town:	"IRVINE"	,	easting:	230900	,	northing:	640200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Irvine Ravenspark Golf Course"	,	town:	"IRVINE"	,	easting:	231300	,	northing:	640700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kilbirnie Place Golf Club"	,	town:	"KILBIRNIE"	,	easting:	230900	,	northing:	654400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lamlash Golf Club"	,	town:	"LAMLASH"	,	easting:	202600	,	northing:	632300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Largs Golf Club"	,	town:	"LARGS"	,	easting:	220900	,	northing:	658200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochranza Golf Course"	,	town:	"LOCHRANZA"	,	easting:	194000	,	northing:	650200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Machrie Bay Golf Club"	,	town:	"BLACKWATERFOOT"	,	easting:	189300	,	northing:	634100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Millport Golf Club"	,	town:	"MILLPORT"	,	easting:	215700	,	northing:	655600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"North Gailes Golf Course"	,	town:	"Irvine"	,	easting:	232238	,	northing:	636167	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Routenburn Golf Course"	,	town:	"LARGS"	,	easting:	220000	,	northing:	660700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Shiskine Golf and Tennis Club"	,	town:	"BLACKWATERFOOT"	,	easting:	189200	,	northing:	628500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Skelmorlie Golf Club"	,	town:	"SKELMORLIE"	,	easting:	220000	,	northing:	667300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Southern Gailes Golf Club"	,	town:	"IRVINE"	,	easting:	232314	,	northing:	636167	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"sportscotland National Centre Inverclyde"	,	town:	"Largs"	,	easting:	221400	,	northing:	660337	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"West Kilbride Golf Club"	,	town:	"WEST KILBRIDE"	,	easting:	219800	,	northing:	647700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Western Gailes Golf Club"	,	town:	"IRVINE"	,	easting:	232300	,	northing:	636100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Whiting Bay Golf Club"	,	town:	"Isle of Arran"	,	easting:	203564	,	northing:	626084	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Airdrie Golf Club"	,	town:	"AIRDRIE"	,	easting:	275500	,	northing:	666900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bellshill Golf Club"	,	town:	"BELLSHILL"	,	easting:	273756	,	northing:	659149	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Calderbraes Golf Club"	,	town:	"UDDINGSTON"	,	easting:	268700	,	northing:	662500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Coatbridge Golf Course and Driving Range"	,	town:	"COATBRIDGE"	,	easting:	271200	,	northing:	666300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Colville Park Country Club"	,	town:	"Motherwell"	,	easting:	275805	,	northing:	658195	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crow Wood Golf Club"	,	town:	"CHRYSTON"	,	easting:	267500	,	northing:	669500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dalziel Park Golf and Country Club"	,	town:	"CLELAND"	,	easting:	278342	,	northing:	657792	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Drumpellier Golf Club"	,	town:	"COATBRIDGE"	,	easting:	271600	,	northing:	664900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dullatur Golf Club"	,	town:	"NR CUMBERNAULD"	,	easting:	274800	,	northing:	676700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dullatur Golf Club"	,	town:	"NR CUMBERNAULD"	,	easting:	274800	,	northing:	676700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Easter Moffat Golf Club"	,	town:	"AIRDRIE"	,	easting:	279800	,	northing:	666100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kilsyth Lennox Golf Club"	,	town:	"KILSYTH"	,	easting:	272134	,	northing:	678715	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochview Family Golf Centre"	,	town:	"Coatbridge"	,	easting:	271160	,	northing:	666316	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Palacerigg Family Golf Centre"	,	town:	"Airdrie"	,	easting:	278342	,	northing:	673699	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Shotts Golf Club"	,	town:	"SHOTTS"	,	easting:	288300	,	northing:	660900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Westerwood Golf And Country Club"	,	town:	"Cumbernauld"	,	easting:	276549	,	northing:	676819	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Wishaw Golf Club"	,	town:	"WISHAW"	,	easting:	278800	,	northing:	655700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"North Ronaldsay Golf Club"	,	town:	"Orkney"	,	easting:	376169	,	northing:	1054633	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Orkney Golf Club"	,	town:	"KIRKWALL"	,	easting:	343600	,	northing:	1011500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Papa Westray Golf Club"	,	town:	"Orkney"	,	easting:	348805	,	northing:	1051891	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Sanday Golf Course"	,	town:	"Orkney"	,	easting:	370543	,	northing:	1041467	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"South Ronaldsay Golf Club"	,	town:	"ST MARGARET'S HOPE"	,	easting:	344586	,	northing:	993054	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Stromness Golf Club"	,	town:	"STROMNESS"	,	easting:	325300	,	northing:	1008100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Westray Golf Club"	,	town:	"Westray"	,	easting:	287740	,	northing:	765132	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Auchterarder Golf Club"	,	town:	"AUCHTERARDER"	,	easting:	293300	,	northing:	712100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bishopshire Golf Club"	,	town:	"NR KINROSS"	,	easting:	317800	,	northing:	702500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Blair Atholl Golf Club"	,	town:	"BLAIR ATHOLL"	,	easting:	287700	,	northing:	765100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Blairgowrie Golf Club"	,	town:	"BLAIRGOWRIE"	,	easting:	318000	,	northing:	743200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Blairgowrie Golf Club"	,	town:	"BLAIRGOWRIE"	,	easting:	318000	,	northing:	743200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Blairgowrie Golf Club"	,	town:	"BLAIRGOWRIE"	,	easting:	318000	,	northing:	743200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Comrie Golf Club"	,	town:	"COMRIE"	,	easting:	277400	,	northing:	722400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Craigie Hill Golf Club"	,	town:	"PERTH"	,	easting:	310200	,	northing:	722500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crieff Golf Club"	,	town:	"CRIEFF"	,	easting:	287200	,	northing:	722300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crieff Golf Club"	,	town:	"CRIEFF"	,	easting:	287200	,	northing:	722300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Crieff Hydro Hotel"	,	town:	"Crieff"	,	easting:	286524	,	northing:	722325	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dalmunzie House Hotel"	,	town:	"BLAIRGOWRIE"	,	easting:	308976	,	northing:	771131	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunkeld and Birnam Golf Club"	,	town:	"DUNKELD"	,	easting:	303200	,	northing:	743100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunning Golf Club"	,	town:	"DUNNING"	,	easting:	301700	,	northing:	714600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Foulford Inn Golf Course"	,	town:	"Crieff"	,	easting:	289149	,	northing:	727013	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glenalmond College"	,	town:	"PERTH"	,	easting:	297624	,	northing:	728724	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gleneagles Hotel"	,	town:	"AUCHTERARDER"	,	easting:	291600	,	northing:	711400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gleneagles Hotel"	,	town:	"AUCHTERARDER"	,	easting:	291600	,	northing:	711400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gleneagles Hotel"	,	town:	"AUCHTERARDER"	,	easting:	291600	,	northing:	711400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Glenisla Golf Course"	,	town:	"Alyth"	,	easting:	325904	,	northing:	748813	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kenmore Golf Club"	,	town:	"ABERFELDY"	,	easting:	277300	,	northing:	746000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"King James VI Golf Club"	,	town:	"PERTH"	,	easting:	312300	,	northing:	722700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kinross Golf Club"	,	town:	"Kinross"	,	easting:	312575	,	northing:	702943	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kinross Golf Club"	,	town:	"Kinross"	,	easting:	312575	,	northing:	702943	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Milnathort Golf Club"	,	town:	"MILNATHORT"	,	easting:	312100	,	northing:	704600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Murrayshall Golf Club"	,	town:	"PERTH"	,	easting:	315500	,	northing:	726000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Murrayshall Golf Club"	,	town:	"PERTH"	,	easting:	315500	,	northing:	726000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Muthill Golf Club"	,	town:	"MUTHILL"	,	easting:	285900	,	northing:	716800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"North Inch Golf Course"	,	town:	"PERTH"	,	easting:	315000	,	northing:	726000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Pitlochry Golf Club"	,	town:	"PITLOCHRY"	,	easting:	293700	,	northing:	758800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Fillans Golf Club"	,	town:	"NR COMRIE"	,	easting:	270300	,	northing:	723700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathmore Golf Centre"	,	town:	"ALYTH"	,	easting:	325265	,	northing:	746190	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathmore Golf Centre"	,	town:	"ALYTH"	,	easting:	325265	,	northing:	746190	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathtay Golf Club"	,	town:	"DUNKELD"	,	easting:	291300	,	northing:	753600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Taymouth Castle Golf Club"	,	town:	"NR ABERFELDY"	,	easting:	278500	,	northing:	746400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Barshaw Golf Course"	,	town:	"PAISLEY"	,	easting:	250000	,	northing:	664300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cochrane Castle Golf Club"	,	town:	"JOHNSTONE"	,	easting:	242300	,	northing:	661600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Elderslie Golf Club"	,	town:	"ELDERSLIE"	,	easting:	245100	,	northing:	663300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Erskine Golf Club"	,	town:	"BISHOPTON"	,	easting:	243500	,	northing:	672100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Gleddoch House Hotel And Golf Club"	,	town:	"Nr Bishopton"	,	easting:	238500	,	northing:	672400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lochwinnoch Golf Club"	,	town:	"LOCHWINNOCH"	,	easting:	234700	,	northing:	659000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Old Ranfurly Golf Club"	,	town:	"BRIDGE OF WEIR"	,	easting:	238400	,	northing:	665200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Paisley Golf Club"	,	town:	"PAISLEY"	,	easting:	246800	,	northing:	660300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ralston Golf Club"	,	town:	"PAISLEY"	,	easting:	250800	,	northing:	663800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ranfurly Castle Golf Club"	,	town:	"BRIDGE OF WEIR"	,	easting:	238100	,	northing:	665400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Renfrew Golf Club"	,	town:	"RENFREW"	,	easting:	250100	,	northing:	668700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cardrona Golf Club"	,	town:	"PEEBLES"	,	easting:	329555	,	northing:	639196	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Duns Golf Club"	,	town:	"DUNS"	,	easting:	376900	,	northing:	653500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Eyemouth Golf Club"	,	town:	"EYEMOUTH"	,	easting:	394700	,	northing:	664300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Galashiels Golf Club"	,	town:	"GALASHIELS"	,	easting:	349400	,	northing:	636700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hawick Golf Club"	,	town:	"Hawick"	,	easting:	349372	,	northing:	613396	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hirsel Golf Club"	,	town:	"COLDSTREAM"	,	easting:	383500	,	northing:	639800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Innerleithen Golf Club"	,	town:	"INNERLEITHEN"	,	easting:	333700	,	northing:	638900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Jedburgh Golf Club"	,	town:	"JEDBURGH"	,	easting:	363600	,	northing:	619600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kelso Golf Club"	,	town:	"KELSO"	,	easting:	372700	,	northing:	635400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lauder Golf Club"	,	town:	"Lauder"	,	easting:	352858	,	northing:	646634	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lilliardsedge Golf Course"	,	town:	"JEDBURGH"	,	easting:	362048	,	northing:	626663	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lilliesleaf Golf Course"	,	town:	"ANCRUM"	,	easting:	350630	,	northing:	622579	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Meadowfield Golf Driving Range"	,	town:	"GALASHIELS"	,	easting:	351871	,	northing:	638274	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Melrose Golf Club"	,	town:	"MELROSE"	,	easting:	354300	,	northing:	633100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newcastleton Golf Club"	,	town:	"NEWCASTLETON"	,	easting:	347900	,	northing:	587800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Peebles Golf Club"	,	town:	"PEEBLES"	,	easting:	324600	,	northing:	640700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Roxburghe Golf Club"	,	town:	"KELSO"	,	easting:	370438	,	northing:	629568	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Selkirk Golf Club"	,	town:	"SELKIRK"	,	easting:	347500	,	northing:	627700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"St Boswells Golf Club"	,	town:	"ST BOSWELLS"	,	easting:	359500	,	northing:	631500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Torwoodlee Golf Club"	,	town:	"GALASHIELS"	,	easting:	347800	,	northing:	638500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"West Linton Golf Club"	,	town:	"WEST LINTON"	,	easting:	312838	,	northing:	651311	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Woll Golf Course"	,	town:	"Selkirk"	,	easting:	345906	,	northing:	621529	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Asta Golf Club"	,	town:	"Shetland, Scotland"	,	easting:	440523	,	northing:	1141904	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Isle of Harris Golf Club"	,	town:	"Isle of Harris"	,	easting:	101146	,	northing:	893610	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Shetland Golf Club"	,	town:	"BRIDGE OF FITCH"	,	easting:	443200	,	northing:	1142300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Whalsay Golf Course"	,	town:	"Shetland"	,	easting:	458832	,	northing:	1166313	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Belleisle & Seafield Golf Courses"	,	town:	"AYR"	,	easting:	233100	,	northing:	619300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Belleisle & Seafield Golf Courses"	,	town:	"AYR"	,	easting:	233100	,	northing:	619300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dalmilling Golf Course"	,	town:	"AYR"	,	easting:	236100	,	northing:	622400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Girvan Golf Course"	,	town:	"GIRVAN"	,	easting:	218400	,	northing:	598600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Green Valley Golf Academy"	,	town:	"Stranraer"	,	easting:	210880	,	northing:	559859	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kilmarnock(Barassie) Golf Club"	,	town:	"TROON"	,	easting:	232900	,	northing:	633100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kilmarnock(Barassie) Golf Club"	,	town:	"TROON"	,	easting:	232900	,	northing:	633100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Maybole Golf Club"	,	town:	"Maybole"	,	easting:	229454	,	northing:	609658	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Prestwick Golf Club"	,	town:	"PRESTWICK"	,	easting:	234500	,	northing:	625300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Prestwick St Cuthbert Golf Club"	,	town:	"PRESTWICK"	,	easting:	235600	,	northing:	624800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Prestwick St Nicholas Golf Club"	,	town:	"PRESTWICK"	,	easting:	234900	,	northing:	626200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Roodlea Golf Centre"	,	town:	"Ayr"	,	easting:	238924	,	northing:	619628	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Troon Golf Club"	,	town:	"TROON"	,	easting:	232800	,	northing:	629700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Troon Golf Club"	,	town:	"TROON"	,	easting:	232800	,	northing:	629700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Royal Troon Golf Club"	,	town:	"TROON"	,	easting:	232800	,	northing:	629700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Troon Municipial Golf Courses"	,	town:	"TROON"	,	easting:	232700	,	northing:	630800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Troon Municipial Golf Courses"	,	town:	"TROON"	,	easting:	232700	,	northing:	630800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Troon Municipial Golf Courses"	,	town:	"TROON"	,	easting:	232700	,	northing:	630800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Turnberry Hotel"	,	town:	"Girvan"	,	easting:	220300	,	northing:	605900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Turnberry Hotel"	,	town:	"Girvan"	,	easting:	220300	,	northing:	605900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Arbory Brae Golf Club"	,	town:	"Biggar"	,	easting:	294915	,	northing:	623921	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Biggar Golf Course"	,	town:	"BIGGAR"	,	easting:	304400	,	northing:	637400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bothwell Castle Golf Club"	,	town:	"BOTHWELL"	,	easting:	270100	,	northing:	658900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Brancumhall Golf Development Centre"	,	town:	"Glasgow"	,	easting:	265490	,	northing:	655414	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cambuslang Golf Club"	,	town:	"GLASGOW"	,	easting:	264500	,	northing:	661000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carluke Golf Club"	,	town:	"CARLUKE"	,	easting:	282692	,	northing:	650755	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Carnwath Golf Club"	,	town:	"CARNWATH"	,	easting:	297200	,	northing:	646500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cathkin Braes Golf Club"	,	town:	"NR RUTHERGLEN"	,	easting:	261600	,	northing:	658300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Douglas Water Golf Club"	,	town:	"LANARK"	,	easting:	287300	,	northing:	634800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"East Kilbride Golf Club"	,	town:	"EAST KILBRIDE"	,	easting:	264600	,	northing:	656500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hamilton Golf Club"	,	town:	"HAMILTON"	,	easting:	274100	,	northing:	653400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hamilton Golf Club"	,	town:	"HAMILTON"	,	easting:	274100	,	northing:	653400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Hollandbush Golf Course"	,	town:	"LESMAHAGOW"	,	easting:	279600	,	northing:	640800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kirkhill Golf Club"	,	town:	"NR CAMBUSLANG"	,	easting:	263800	,	northing:	658900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lanark Golf Club"	,	town:	"LANARK"	,	easting:	289800	,	northing:	643200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Lanark Golf Club"	,	town:	"LANARK"	,	easting:	289800	,	northing:	643200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Langlands Golf Course"	,	town:	"EAST KILBRIDE"	,	easting:	262313	,	northing:	650375	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Larkhall Golf Course"	,	town:	"LARKHALL"	,	easting:	276000	,	northing:	651000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Leadhills Golf Club"	,	town:	"LEADHILLS"	,	easting:	288784	,	northing:	614632	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Playsport Golf Club (Heritage Links)"	,	town:	"Glasgow"	,	easting:	263465	,	northing:	656620	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathaven Golf Club"	,	town:	"STRATHAVEN"	,	easting:	270000	,	northing:	645600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathclyde Park Golf Course"	,	town:	"HAMILTON"	,	easting:	272300	,	northing:	656200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Torrance House Golf Course"	,	town:	"EAST KILBRIDE"	,	easting:	265400	,	northing:	652600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aberfoyle Golf Club"	,	town:	"ABERFOYLE"	,	easting:	253400	,	northing:	700500	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Balfron Shian Golf Course"	,	town:	"Stirling"	,	easting:	254555	,	northing:	689369	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bridge of Allan Golf Club"	,	town:	"BRIDGE OF ALLAN"	,	easting:	279177	,	northing:	698368	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Brucefields Family Golf Centre"	,	town:	"BANNOCKBURN"	,	easting:	280868	,	northing:	689580	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Buchanan Castle Golf Club"	,	town:	"Drymen"	,	easting:	245700	,	northing:	688800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Callander Golf Club"	,	town:	"CALLANDER"	,	easting:	263900	,	northing:	707400	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dunblane New Golf Club"	,	town:	"DUNBLANE"	,	easting:	278300	,	northing:	701000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Killin Golf Club"	,	town:	"KILLIN"	,	easting:	257100	,	northing:	734200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Stirling Golf Club"	,	town:	"STIRLING"	,	easting:	278700	,	northing:	693300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Strathendrick Golf Club"	,	town:	"Glasgow"	,	easting:	248698	,	northing:	689134	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Cameron House Hotel And Country Club"	,	town:	"Alexandria"	,	easting:	237472	,	northing:	683105	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Clydebank & District Golf Club"	,	town:	"DUNTOCHER"	,	easting:	250300	,	northing:	672600	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Clydebank Overtoun Golf Club"	,	town:	"CLYDEBANK"	,	easting:	248300	,	northing:	671800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Dumbarton Golf Club"	,	town:	"DUMBARTON"	,	easting:	239800	,	northing:	676200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Ross Priory Golf Club"	,	town:	"ALEXANDRIA"	,	easting:	241462	,	northing:	687567	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Vale of Leven Golf Club"	,	town:	"ALEXANDRIA"	,	easting:	240100	,	northing:	680100	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bathgate Golf Club"	,	town:	"BATHGATE"	,	easting:	297500	,	northing:	668300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Bridgend and District Golf Club"	,	town:	"Linlithgow"	,	easting:	303967	,	northing:	675616	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Deer Park Golf And Country Club"	,	town:	"Livingston"	,	easting:	304200	,	northing:	669800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Greenburn Golf Club"	,	town:	"FAULDHOUSE"	,	easting:	293400	,	northing:	660200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Harburn Golf Club"	,	town:	"West Calder"	,	easting:	301981	,	northing:	663077	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Kingsfield Golf Range"	,	town:	"Linlithgow"	,	easting:	302697	,	northing:	677871	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Linlithgow Golf Club"	,	town:	"LINLITHGOW"	,	easting:	298800	,	northing:	675900	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Niddry Castle Golf Club"	,	town:	"WINCHBURGH"	,	easting:	309400	,	northing:	674700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Oatridge College"	,	town:	"UPHALL"	,	easting:	305500	,	northing:	673700	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Oatridge Golf Course"	,	town:	"Broxburn"	,	easting:	304757	,	northing:	672911	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Polkemmet Golf Course"	,	town:	"BATHGATE"	,	easting:	292700	,	northing:	664800	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Pumpherston Golf Course"	,	town:	"NR LIVINGSTON"	,	easting:	307200	,	northing:	669200	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Uphall Golf Club"	,	town:	"UPHALL"	,	easting:	305500	,	northing:	671300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"West Lothian Golf Club"	,	town:	"LINLITHGOW"	,	easting:	300400	,	northing:	679300	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Newmacher Golf Club"	,	town:	"NEWMACHER"	,	easting:	388200	,	northing:	817000	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Nuffield Health Milngavie"	,	town:	"Glasgow"	,	easting:	256538	,	northing:	675277	,	facility_sub_type:	"Golf Course" },	
{ site_name:	"Aberfeldy Golf Club"	,	town:	"ABERFELDY"	,	easting:	285100	,	northing:	749300	,	facility_sub_type:	"Golf Course" }	

];
